# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.19

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.19.2/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.19.2/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/tanknee/Documents/LocalCodeRepo/DigitalImageProcess/opencv

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/tanknee/Documents/LocalCodeRepo/DigitalImageProcess/build_js

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"dev\" \"libs\" \"licenses\" \"scripts\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.19.2/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/Cellar/cmake/3.19.2/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/Cellar/cmake/3.19.2/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/local/Cellar/cmake/3.19.2/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test

.PHONY : test/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.19.2/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool for source..."
	/usr/local/Cellar/cmake/3.19.2/bin/cpack --config ./CPackSourceConfig.cmake /Users/tanknee/Documents/LocalCodeRepo/DigitalImageProcess/build_js/CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source

.PHONY : package_source/fast

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool..."
	/usr/local/Cellar/cmake/3.19.2/bin/cpack --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package

.PHONY : package/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/Cellar/cmake/3.19.2/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/Cellar/cmake/3.19.2/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/Cellar/cmake/3.19.2/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/Cellar/cmake/3.19.2/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/tanknee/Documents/LocalCodeRepo/DigitalImageProcess/build_js/CMakeFiles /Users/tanknee/Documents/LocalCodeRepo/DigitalImageProcess/build_js//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/tanknee/Documents/LocalCodeRepo/DigitalImageProcess/build_js/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named opencv_modules

# Build rule for target.
opencv_modules: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 opencv_modules
.PHONY : opencv_modules

# fast build rule for target.
opencv_modules/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/opencv_modules.dir/build.make CMakeFiles/opencv_modules.dir/build
.PHONY : opencv_modules/fast

#=============================================================================
# Target rules for targets named uninstall

# Build rule for target.
uninstall: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 uninstall
.PHONY : uninstall

# fast build rule for target.
uninstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/uninstall.dir/build.make CMakeFiles/uninstall.dir/build
.PHONY : uninstall/fast

#=============================================================================
# Target rules for targets named zlib

# Build rule for target.
zlib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 zlib
.PHONY : zlib

# fast build rule for target.
zlib/fast:
	$(MAKE) $(MAKESILENT) -f 3rdparty/zlib/CMakeFiles/zlib.dir/build.make 3rdparty/zlib/CMakeFiles/zlib.dir/build
.PHONY : zlib/fast

#=============================================================================
# Target rules for targets named libopenjp2

# Build rule for target.
libopenjp2: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 libopenjp2
.PHONY : libopenjp2

# fast build rule for target.
libopenjp2/fast:
	$(MAKE) $(MAKESILENT) -f 3rdparty/openjpeg/openjp2/CMakeFiles/libopenjp2.dir/build.make 3rdparty/openjpeg/openjp2/CMakeFiles/libopenjp2.dir/build
.PHONY : libopenjp2/fast

#=============================================================================
# Target rules for targets named libprotobuf

# Build rule for target.
libprotobuf: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 libprotobuf
.PHONY : libprotobuf

# fast build rule for target.
libprotobuf/fast:
	$(MAKE) $(MAKESILENT) -f 3rdparty/protobuf/CMakeFiles/libprotobuf.dir/build.make 3rdparty/protobuf/CMakeFiles/libprotobuf.dir/build
.PHONY : libprotobuf/fast

#=============================================================================
# Target rules for targets named opencv_videoio_plugins

# Build rule for target.
opencv_videoio_plugins: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 opencv_videoio_plugins
.PHONY : opencv_videoio_plugins

# fast build rule for target.
opencv_videoio_plugins/fast:
	$(MAKE) $(MAKESILENT) -f modules/.firstpass/videoio/CMakeFiles/opencv_videoio_plugins.dir/build.make modules/.firstpass/videoio/CMakeFiles/opencv_videoio_plugins.dir/build
.PHONY : opencv_videoio_plugins/fast

#=============================================================================
# Target rules for targets named opencv_core

# Build rule for target.
opencv_core: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 opencv_core
.PHONY : opencv_core

# fast build rule for target.
opencv_core/fast:
	$(MAKE) $(MAKESILENT) -f modules/core/CMakeFiles/opencv_core.dir/build.make modules/core/CMakeFiles/opencv_core.dir/build
.PHONY : opencv_core/fast

#=============================================================================
# Target rules for targets named opencv_flann

# Build rule for target.
opencv_flann: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 opencv_flann
.PHONY : opencv_flann

# fast build rule for target.
opencv_flann/fast:
	$(MAKE) $(MAKESILENT) -f modules/flann/CMakeFiles/opencv_flann.dir/build.make modules/flann/CMakeFiles/opencv_flann.dir/build
.PHONY : opencv_flann/fast

#=============================================================================
# Target rules for targets named opencv_imgproc

# Build rule for target.
opencv_imgproc: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 opencv_imgproc
.PHONY : opencv_imgproc

# fast build rule for target.
opencv_imgproc/fast:
	$(MAKE) $(MAKESILENT) -f modules/imgproc/CMakeFiles/opencv_imgproc.dir/build.make modules/imgproc/CMakeFiles/opencv_imgproc.dir/build
.PHONY : opencv_imgproc/fast

#=============================================================================
# Target rules for targets named opencv_photo

# Build rule for target.
opencv_photo: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 opencv_photo
.PHONY : opencv_photo

# fast build rule for target.
opencv_photo/fast:
	$(MAKE) $(MAKESILENT) -f modules/photo/CMakeFiles/opencv_photo.dir/build.make modules/photo/CMakeFiles/opencv_photo.dir/build
.PHONY : opencv_photo/fast

#=============================================================================
# Target rules for targets named opencv_dnn

# Build rule for target.
opencv_dnn: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 opencv_dnn
.PHONY : opencv_dnn

# fast build rule for target.
opencv_dnn/fast:
	$(MAKE) $(MAKESILENT) -f modules/dnn/CMakeFiles/opencv_dnn.dir/build.make modules/dnn/CMakeFiles/opencv_dnn.dir/build
.PHONY : opencv_dnn/fast

#=============================================================================
# Target rules for targets named opencv_features2d

# Build rule for target.
opencv_features2d: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 opencv_features2d
.PHONY : opencv_features2d

# fast build rule for target.
opencv_features2d/fast:
	$(MAKE) $(MAKESILENT) -f modules/features2d/CMakeFiles/opencv_features2d.dir/build.make modules/features2d/CMakeFiles/opencv_features2d.dir/build
.PHONY : opencv_features2d/fast

#=============================================================================
# Target rules for targets named opencv_calib3d

# Build rule for target.
opencv_calib3d: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 opencv_calib3d
.PHONY : opencv_calib3d

# fast build rule for target.
opencv_calib3d/fast:
	$(MAKE) $(MAKESILENT) -f modules/calib3d/CMakeFiles/opencv_calib3d.dir/build.make modules/calib3d/CMakeFiles/opencv_calib3d.dir/build
.PHONY : opencv_calib3d/fast

#=============================================================================
# Target rules for targets named opencv_objdetect

# Build rule for target.
opencv_objdetect: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 opencv_objdetect
.PHONY : opencv_objdetect

# fast build rule for target.
opencv_objdetect/fast:
	$(MAKE) $(MAKESILENT) -f modules/objdetect/CMakeFiles/opencv_objdetect.dir/build.make modules/objdetect/CMakeFiles/opencv_objdetect.dir/build
.PHONY : opencv_objdetect/fast

#=============================================================================
# Target rules for targets named opencv_video

# Build rule for target.
opencv_video: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 opencv_video
.PHONY : opencv_video

# fast build rule for target.
opencv_video/fast:
	$(MAKE) $(MAKESILENT) -f modules/video/CMakeFiles/opencv_video.dir/build.make modules/video/CMakeFiles/opencv_video.dir/build
.PHONY : opencv_video/fast

#=============================================================================
# Target rules for targets named gen_opencv_java_source

# Build rule for target.
gen_opencv_java_source: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gen_opencv_java_source
.PHONY : gen_opencv_java_source

# fast build rule for target.
gen_opencv_java_source/fast:
	$(MAKE) $(MAKESILENT) -f modules/java_bindings_generator/CMakeFiles/gen_opencv_java_source.dir/build.make modules/java_bindings_generator/CMakeFiles/gen_opencv_java_source.dir/build
.PHONY : gen_opencv_java_source/fast

#=============================================================================
# Target rules for targets named gen_opencv_js_source

# Build rule for target.
gen_opencv_js_source: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gen_opencv_js_source
.PHONY : gen_opencv_js_source

# fast build rule for target.
gen_opencv_js_source/fast:
	$(MAKE) $(MAKESILENT) -f modules/js_bindings_generator/CMakeFiles/gen_opencv_js_source.dir/build.make modules/js_bindings_generator/CMakeFiles/gen_opencv_js_source.dir/build
.PHONY : gen_opencv_js_source/fast

#=============================================================================
# Target rules for targets named gen_opencv_objc_source_osx

# Build rule for target.
gen_opencv_objc_source_osx: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gen_opencv_objc_source_osx
.PHONY : gen_opencv_objc_source_osx

# fast build rule for target.
gen_opencv_objc_source_osx/fast:
	$(MAKE) $(MAKESILENT) -f modules/objc_bindings_generator/CMakeFiles/gen_opencv_objc_source_osx.dir/build.make modules/objc_bindings_generator/CMakeFiles/gen_opencv_objc_source_osx.dir/build
.PHONY : gen_opencv_objc_source_osx/fast

#=============================================================================
# Target rules for targets named gen_opencv_objc_source_ios

# Build rule for target.
gen_opencv_objc_source_ios: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gen_opencv_objc_source_ios
.PHONY : gen_opencv_objc_source_ios

# fast build rule for target.
gen_opencv_objc_source_ios/fast:
	$(MAKE) $(MAKESILENT) -f modules/objc_bindings_generator/CMakeFiles/gen_opencv_objc_source_ios.dir/build.make modules/objc_bindings_generator/CMakeFiles/gen_opencv_objc_source_ios.dir/build
.PHONY : gen_opencv_objc_source_ios/fast

#=============================================================================
# Target rules for targets named gen_opencv_objc_source

# Build rule for target.
gen_opencv_objc_source: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gen_opencv_objc_source
.PHONY : gen_opencv_objc_source

# fast build rule for target.
gen_opencv_objc_source/fast:
	$(MAKE) $(MAKESILENT) -f modules/objc_bindings_generator/CMakeFiles/gen_opencv_objc_source.dir/build.make modules/objc_bindings_generator/CMakeFiles/gen_opencv_objc_source.dir/build
.PHONY : gen_opencv_objc_source/fast

#=============================================================================
# Target rules for targets named gen_opencv_python_source

# Build rule for target.
gen_opencv_python_source: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gen_opencv_python_source
.PHONY : gen_opencv_python_source

# fast build rule for target.
gen_opencv_python_source/fast:
	$(MAKE) $(MAKESILENT) -f modules/python_bindings_generator/CMakeFiles/gen_opencv_python_source.dir/build.make modules/python_bindings_generator/CMakeFiles/gen_opencv_python_source.dir/build
.PHONY : gen_opencv_python_source/fast

#=============================================================================
# Target rules for targets named opencv_test_js

# Build rule for target.
opencv_test_js: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 opencv_test_js
.PHONY : opencv_test_js

# fast build rule for target.
opencv_test_js/fast:
	$(MAKE) $(MAKESILENT) -f modules/js/CMakeFiles/opencv_test_js.dir/build.make modules/js/CMakeFiles/opencv_test_js.dir/build
.PHONY : opencv_test_js/fast

#=============================================================================
# Target rules for targets named opencv_js_loader

# Build rule for target.
opencv_js_loader: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 opencv_js_loader
.PHONY : opencv_js_loader

# fast build rule for target.
opencv_js_loader/fast:
	$(MAKE) $(MAKESILENT) -f modules/js/CMakeFiles/opencv_js_loader.dir/build.make modules/js/CMakeFiles/opencv_js_loader.dir/build
.PHONY : opencv_js_loader/fast

#=============================================================================
# Target rules for targets named opencv_js_perf

# Build rule for target.
opencv_js_perf: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 opencv_js_perf
.PHONY : opencv_js_perf

# fast build rule for target.
opencv_js_perf/fast:
	$(MAKE) $(MAKESILENT) -f modules/js/CMakeFiles/opencv_js_perf.dir/build.make modules/js/CMakeFiles/opencv_js_perf.dir/build
.PHONY : opencv_js_perf/fast

#=============================================================================
# Target rules for targets named opencv.js

# Build rule for target.
opencv.js: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 opencv.js
.PHONY : opencv.js

# fast build rule for target.
opencv.js/fast:
	$(MAKE) $(MAKESILENT) -f modules/js/CMakeFiles/opencv.js.dir/build.make modules/js/CMakeFiles/opencv.js.dir/build
.PHONY : opencv.js/fast

#=============================================================================
# Target rules for targets named opencv_js_test

# Build rule for target.
opencv_js_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 opencv_js_test
.PHONY : opencv_js_test

# fast build rule for target.
opencv_js_test/fast:
	$(MAKE) $(MAKESILENT) -f modules/js/CMakeFiles/opencv_js_test.dir/build.make modules/js/CMakeFiles/opencv_js_test.dir/build
.PHONY : opencv_js_test/fast

#=============================================================================
# Target rules for targets named opencv_js

# Build rule for target.
opencv_js: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 opencv_js
.PHONY : opencv_js

# fast build rule for target.
opencv_js/fast:
	$(MAKE) $(MAKESILENT) -f modules/js/CMakeFiles/opencv_js.dir/build.make modules/js/CMakeFiles/opencv_js.dir/build
.PHONY : opencv_js/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... package"
	@echo "... package_source"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... gen_opencv_java_source"
	@echo "... gen_opencv_js_source"
	@echo "... gen_opencv_objc_source"
	@echo "... gen_opencv_objc_source_ios"
	@echo "... gen_opencv_objc_source_osx"
	@echo "... gen_opencv_python_source"
	@echo "... opencv.js"
	@echo "... opencv_js_loader"
	@echo "... opencv_js_perf"
	@echo "... opencv_js_test"
	@echo "... opencv_modules"
	@echo "... opencv_test_js"
	@echo "... opencv_videoio_plugins"
	@echo "... uninstall"
	@echo "... libopenjp2"
	@echo "... libprotobuf"
	@echo "... opencv_calib3d"
	@echo "... opencv_core"
	@echo "... opencv_dnn"
	@echo "... opencv_features2d"
	@echo "... opencv_flann"
	@echo "... opencv_imgproc"
	@echo "... opencv_js"
	@echo "... opencv_objdetect"
	@echo "... opencv_photo"
	@echo "... opencv_video"
	@echo "... zlib"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

